autochanger test: unlock every tape device on startup

diff --git a/systemtests/tests/autochanger/test-setup b/systemtests/tests/autochanger/test-setup
--- a/systemtests/tests/autochanger/test-setup
+++ b/systemtests/tests/autochanger/test-setup
@@ -32,15 +32,17 @@ set -u
 "${rscripts}"/setup
 
 
-if ! ./invalidate_tapes.sh ${1:-}
-then
-  echo "Could not invalidate tapes"
-  exit 1
-fi
 
 if ! ./create_autochanger_configs.sh ${1:-}
 then
   echo "Could not create autochanger configs"
+  exit 1
+fi
+
+
+if ! ./invalidate_tapes.sh ${1:-}
+then
+  echo "Could not invalidate tapes"
   exit 1
 fi
 
