tests: fix some ignored warnings in tests

diff --git a/systemtests/scripts/functions b/systemtests/scripts/functions
--- a/systemtests/scripts/functions
+++ b/systemtests/scripts/functions
@@ -809,20 +809,21 @@ check_two_logs()
   default_restore_log="${tmp}/log2.out"
   restore_log=${2:-${default_restore_log}}
 
-  if grep "^  Termination: *Backup OK" "$backup_log" >/dev/null 2>&1; then
-    bstat=${bstat:-$?}
-  fi
-
-  if grep "^  Termination: .*Backup Error" "$backup_log" >/dev/null 2>&1; then
+  if ! grep "^  Termination: *Backup OK$" "$backup_log" >/dev/null 2>&1; then
     echo "Backup error!"
     bstat=2
   fi
 
-  if grep "^  Termination: *Restore OK" "$restore_log" >/dev/null 2>&1; then
+  if grep "^  Termination: .*Backup Error$" "$backup_log" >/dev/null 2>&1; then
+    echo "Backup error!"
+    bstat=2
+  fi
+
+  if grep "^  Termination: *Restore OK$" "$restore_log" >/dev/null 2>&1; then
     rstat=${rstat:-$?}
   fi
 
-  if grep "^  Termination: .*Restore Error" "$restore_log" >/dev/null 2>&1; then
+  if grep "^  Termination: .*Restore Error$" "$restore_log" >/dev/null 2>&1; then
     echo "Restore error!"
     rstat=2
   fi
@@ -853,6 +854,7 @@ check_log()
 
   if grep \
     -e "^  Termination: .*Backup Error" \
+    -e "^  Termination: .*Backup OK -- with warnings" \
     -e "^Can't find " \
     -e "Encoding error for database" \
     -e "^Could not find Client" \
@@ -867,7 +869,7 @@ check_log()
 
   if grep \
     -e "^  Termination: .*Restore Error" \
-    -e "^  Termination: *Restore OK -- warning" \
+    -e "^  Termination: *Restore OK -- with warnings" \
     -e "^  Termination: .*Verify Differences" \
     "$LOG"; then
     rstat=1
